[MM-29157] Invoices endpoints for cloud
mattermost/mattermost-api-reference pull request #583
Opened 2020-10-22 19:36 UTC by ethervoid

#### Summary

This PR the new cloud endpoints docs for invoices

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-29157

2020-10-22 21:18 UTC, marianunez requested changes

2020-10-22 21:18 UTC, marianunez commented on v4/source/cloud.yaml
> +        __Minimum server version__: 5.28
I think this should be 5.30? Not that it matters for us but technically is not in 5.28 because that was released already

2020-10-23 13:21 UTC, nickmisasi approved these changes
One nit, and I think Maria's right about 5.28 - otherwise, LGTM!

2020-10-23 13:21 UTC, nickmisasi commented on v4/source/cloud.yaml
> +        Retrieves the invoices for the subscriptio bound to this installation.
```suggestion
        Retrieves the invoices for the subscription bound to this installation.
```

2020-10-26 19:13 UTC, marianunez approved these changes

2020-10-26 19:14 UTC, merged