[MM-31790] Support Packet Generation DOCUMENTATION
mattermost/mattermost-api-reference pull request #599
Opened 2021-01-11 21:21 UTC by hahmadia

#### Summary

This is the documentation for the support packet generation endpoint which can be found at https://github.com/mattermost/mattermost-server/pull/16667

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-31790

2021-01-13 00:21 UTC, sbishel requested changes

2021-01-13 00:21 UTC, sbishel commented on v4/source/system.yaml
> +  /system/generate_support_packet:
```suggestion
  /system/support_packet:
```

2021-01-15 20:32 UTC, sbishel approved these changes

2021-01-21 00:40 UTC, mkraft approved these changes

2021-02-01 20:18 UTC, merged