[MM-32543] - Add spec for cloud/alert/admin
mattermost/mattermost-api-reference pull request #607
Opened 2021-02-08 09:34 UTC by AGMETEOR

#### Summary
This is the spec definition for the endpoint ```cloud/alert/admin``` that adds rate limited way for users to alert sysadmins about free tier user count limitation

#### Ticket Link
[MM-32543](https://mattermost.atlassian.net/secure/RapidBoard.jspa?rapidView=79&projectKey=MM&modal=detail&selectedIssue=MM-32543&quickFilter=382)

2021-02-10 20:03 UTC, marianunez approved these changes
LGTM, could you update the PR name and description to the new endpoint name?

Thanks @AGMETEOR!

2021-02-12 09:30 UTC, ethervoid requested changes

2021-02-12 09:30 UTC, ethervoid commented on v4/source/cloud.yaml
> +          description: Atleast one sys admin received the an email
```suggestion
          description: Email sent to at least one of the system administrators
```

2021-02-12 09:30 UTC, ethervoid commented on v4/source/cloud.yaml
> +          $ref: "#/components/responses/TooLarge"
```suggestion
        "429:
          $ref: "#/components/responses/TooManyRequests"
```

2021-02-15 17:26 UTC, marianunez commented on v4/source/cloud.yaml
> +          $ref: "#/components/responses/TooManyRequests"
This should be set back to 413 as originally implemented

```suggestion
        "413":
          $ref: "#/components/responses/TooLarge"
```

2021-02-15 21:23 UTC, ethervoid approved these changes
LGTM!

2021-02-15 21:23 UTC, merged