[Fix - #586] : Change property type of PluginStatus.state from number to string.
mattermost/mattermost-api-reference pull request #611
Opened 2021-02-16 14:26 UTC by haardikdharma10

#### Summary

Fixes : #586

2021-02-16 14:27 UTC, mattermod commented
Hello @haardikdharma10,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-02-17 06:42 UTC, hanzei approved these changes

2021-02-17 14:20 UTC, lieut-data requested changes
Thanks for the recommendation, @haardikdharma10! Can you help me understand the problem here?

If I look at the definition of a `PluginStatus` in the model, the `state` is indeed a number that is described by various enumerated values:

https://github.com/mattermost/mattermost-server/blob/8e71ab1ecb4d05df5c13652bd3f0c8c4e8d9b0e6/model/plugin_status.go#L11-L29

Was there something you ran into that suggested otherwise? Or perhaps there is a different way to improve the documentation to reflect this?

2021-02-28 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-03-01 17:21 UTC, lieut-data commented
@haardikdharma10, let me know if this PR is still on your radar -- happy to continue the conversation to improve the developer experience here :)

2021-03-01 20:39 UTC, haardikdharma10 commented
Sorry for the delay @lieut-data. After having a word with @hanzei once again, we decided it should be closed :)

2021-03-01 20:39 UTC, closed without merging