[MM-42742] Top Reactions Documentation
mattermost/mattermost-api-reference pull request #692
Opened 2022-04-14 18:22 UTC by mylonsuren

#### Summary

Adds documentation for the top reactions for team/user endpoint. This endpoint is currently hidden behind a feature flag.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-42742

2022-04-18 13:59 UTC, mkraft requested changes

2022-04-18 16:46 UTC, mylonsuren commented on v4/source/reactions.yaml
> +        Must have insights enabled.
Ok that makes sense, I had included it just to be safe, but I've removed it now so should be good.

2022-04-19 12:59 UTC, mkraft approved these changes

2022-04-19 16:20 UTC, cwarnermm commented on v4/source/definitions.yaml
> +          description: The name of the emoji that was used for this reaction
```suggestion
          description: The name of the emoji used for this reaction.
```

2022-04-19 17:17 UTC, cwarnermm reviewed
Thank you, @mylonsuren!, for this great docs update! I've provided feedback inline. The majority of feedback is on punctuation consistency.

2022-04-19 17:17 UTC, cwarnermm commented on v4/source/reactions.yaml
> +            - `7_day`: reactions posted in the last 7 days
```suggestion
            - `7_day`: reactions posted in the last 7 days.
```

2022-04-19 17:17 UTC, cwarnermm commented on v4/source/reactions.yaml
> +            - `28_day`: reactions posted in the last 28 days
```suggestion
            - `28_day`: reactions posted in the last 28 days.
```

2022-04-19 17:17 UTC, cwarnermm commented on v4/source/reactions.yaml
> +          description: The number of reactions per page. There is a maximum limit of 200 reactions per page.
```suggestion
          description: The number of reactions per page, up to a maximum of 200.
```

2022-04-19 17:17 UTC, cwarnermm commented on v4/source/reactions.yaml
> +          description: Top reactions retrieve successful
Could rewording this to "Top reactions retrieved successfully." work?

2022-04-19 17:17 UTC, cwarnermm commented on v4/source/reactions.yaml
> +      summary: Get a list of the top reactions for a user
Please review for technical accuracy. I attempted to write this in a parallel way to the teams equivalent.

2022-04-19 17:17 UTC, cwarnermm commented on v4/source/reactions.yaml
> +            Time Range can be "today", "7_day" or "28_day".
```suggestion
            Time range can be "today", "7_day", or "28_day".
```

2022-04-20 17:56 UTC, mylonsuren commented on v4/source/definitions.yaml
> +          description: The name of the emoji that was used for this reaction
Yes, they're both referring to the same field.

2022-04-20 18:02 UTC, mylonsuren commented on v4/source/reactions.yaml
> +      summary: Get a list of the top reactions for a user
Yes that makes sense, thanks for adding the extra detail.

2022-04-20 18:07 UTC, mylonsuren commented
@cwarnermm The changes you've requested have been added now, thanks for the feedback! Just double checking that this is OK to merge?

2022-04-20 18:08 UTC, cwarnermm commented
Thanks @mylonsuren! We're ready to merge from my perspective.

2022-04-20 18:09 UTC, merged